### ISSUE TITLE
Access to paths in w10 iot using Core

### ISSUE THREAD

**Issue by alexjoei** [jeremylindsayni/Bifrost#8]
Hey,
Im having some problems while using your libraries to manage gpio on mi rb pi 3 from my aspnet webapi core 2. When calling GpioController.Instance an error ocurred:

> _### fail: Microsoft.AspNetCore.Server.Kestrel[13]
>       Connection id "0HLB05C1JH9C2", Request id "0HLB05C1JH9C2:00000001": An unhandled exception was thrown by the application.
> System.Exception: Could not find device path for Windows application ---> System.InvalidOperationException: Sequence contains no matching element
>    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Bifrost.Devices.Gpio.GpioController.get_Instance() in C:\Users\alejandro\Documents\Visual Studio 2017\Projects\HomeApplication\Bifrost.Devices.Gpio\GpioController.cs:line 35
>    --- End of inner exception stack trace ---
>    at Bifrost.Devices.Gpio.GpioController.get_Instance() in C:\Users\alejandro\Documents\Visual Studio 2017\Projects\HomeApplication\Bifrost.Devices.Gpio\GpioController.cs:line 43_

I obtained this error changing the references from nuget straight to your projects downloaded. Trying to figure it out, but probably you could be faster than me. Thanks in advance, let you know if i find smth.

**Comment by jeremylindsayni** [comment]
Hey - thank you for raising the issue!

Can I ask - since you are running on Windows 10 IoT Core, are you running the Bifrost device bridge?

The code and read me is here: https://github.com/jeremylindsayni/Bifrost/tree/master/Bifrost.Devices.Bridge

There's also a blog post here, the first half describes how to deploy the UWP app - https://jeremylindsayni.wordpress.com/2017/04/18/write-net-core-2-once-run-anywhere-hardware-access-on-raspberry-pi-3-with-ubuntu-and-windows-10-iot-core/

Bifrost is a lot more opinionated on Windows than it is on Linux. Basically Windows 10 IoT Core only allows access to the GPIO pins through it's own API, so the device bridge is a UWP app which needs to be running on the IoT device as well.

Could you give that a try and then re-run your website on the Pi3 please?

The error message needs to be more informative - it hasn't found the directory, but on the basis of the OS it could probably advise that the UWP bridge isn't running or installed.

**Comment by alexjoei** [comment]
Hey, thanks for the advice. I finally was able to activate and use Bifrost on my rbpi3. Anyway, Although I turn the light on setting the gpio to 1 using Bifrost, once I have done it the first time, then i turn the value to 0, but the light don't turns off. But in this moment. 

If I stop bifrost App(from the windows device portal) the light turns on, so I can assure the value is changed(I also see the file manually) but I don't know exactly why, Bifrost is not sending that new value to GPIO..?. 

Of course, if I restart Bifrost, it read the value(0 or 1) and turns the light off or on correctly, I make the first change, it takes effect on the file and the light, but the second time the file is updated but the action don't take effects on the light. If you have any idea it will be welcome, I guess its some basic thing I'm missing..,maybe related with dispossing..

**Comment by jeremylindsayni** [comment]
Hi there - so just to clarify - setting the GPIO value to 1 turns the light on, but then setting it to 0 doesn't turn it off, is that correct?

It sounds like the FileSystemWatcher isn't registering the change for some reason.

Could you please paste the class that you've written to turn the light on and off? That would help me recreate the issue.

**Comment by alexjoei** [comment]
Hey,
- Not exactly, its not relevant setting the 0 or 1, the issue is that at the beginning, 1,2 or 3 times, it turns the light on or off correctly, but after that stop responding. The values are correct in the files, but it takes no effect on GPIO(light in this case)
- Yep, I think is something like that with the FileSystemWatcher or disposing the GPIO pin...no idea but Im stucked.

- I have used those libraries

_Install-Package Bifrost.Devices.Gpio.Core -Version 0.0.1
Install-Package Bifrost.Devices.Gpio.Abstractions -Version 0.0.1
Install-Package Bifrost.Devices.Gpio -Version 0.0.2_

And this code

public class GPIOService : IGPIOService
    {
        private IGpioController gpioController;

        public GPIOService()
        {
            gpioController = GpioController.Instance;
        }

        public void SetState(int gpioId, bool value)
        {
            var pin = gpioController.OpenPin(gpioId);

            pin.SetDriveMode(GpioPinDriveMode.Output);

            pin.Write(value ? GpioPinValue.High : GpioPinValue.Low);

        }
    }

Also tried this one trying to change something regarding dispossing but it doesn't work neither:

_public void SetState(int gpioId, bool value)
        {
            using (IGpioPin pin = gpioController.OpenPin(gpioId))
            {
                pin.SetDriveMode(GpioPinDriveMode.Output);
                pin.Write(value ? GpioPinValue.High : GpioPinValue.Low);
            }
        }_
